name: vocab_hero
description: The Ultimate English Vocabulary Learning App for Bangladesh

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Audio & Speech
  audioplayers: ^5.2.1
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Storage & Data
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Networking
  http: ^1.1.0
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1
  
  # Animations & Haptics
  flutter_animate: ^4.2.0+1
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/audio/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
        - asset: assets/fonts/HindSiliguri-Medium.ttf
          weight: 500
        - asset: assets/fonts/HindSiliguri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/HindSiliguri-Bold.ttf
          weight: 700
